[tool.poetry]
name = "trustyai-service"
version = "1.0.0rc0"
description = "TrustyAI Service"
authors = ["Rui Vieira", "TrustyAI team"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.9"
pandas = "^2.2.3"
prometheus-client = "^0.21.1"
pydantic = "^2.4.2"
uvicorn = "^0.34.0"
cryptography =  "^44.0.2"
protobuf = "^4.24.4"
requests = "^2.31.0"
h5py = "^3.13.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
isort = "^5.12.0"
flake8 = "^6.1.0"
mypy = "^1.5.1"
pytest-cov = "^4.1.0"
httpx = "^0.25.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
warn_unused_ignores = true

[tool.ruff]
preview = true
line-length = 120
fix = true
output-format = "grouped"
extend-exclude = ["utilities/manifests"]

[tool.ruff.format]
exclude = [".git", ".venv", ".mypy_cache", "__pycache__"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
